# Generated by Django 4.1.7 on 2024-06-10 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_remove_new_view_home_category_view_home'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='sub_category',
            field=models.ManyToManyField(blank=True, to='news.subcategory'),
        ),
    ]
